name: CD

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install uv and Python
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.9"
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Sync dependencies
        run: uv sync --locked --all-extras --all-groups
      - name: Build package
        run: uv build
      - name: Publish publish-package
        run: uv publish --token ${{ secrets.PYPI_TOKEN }}
